export interface LoanApplicationDocuments {
  labelName: string;
  controlName: string;
  numberOfDocs: number;
  maxUploadSize: number;
  fileExtensionType: string;
  addInformation: any;
  required: boolean;
}

export const documentRequiredByAgriBussinessSector: LoanApplicationDocuments[] = [
  {
    labelName: 'Audited Financial Statements',
    controlName: 'auditedFinancialStatements',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Application Form and Business Plan',
    controlName: 'applicationFormAndBusinessPlan',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Business Bank Statement for 6 Months',
    controlName: 'businessBankStatementFor6months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Certified Copies of Omang',
    controlName: 'certifiedCopiesOfOmang',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Resolution by Board of Directors',
    controlName: 'resolutionByBod',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 2',
    controlName: 'form2',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 3',
    controlName: 'form3',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 4',
    controlName: 'form4',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Provisional Offer of Land',
    controlName: 'provisionalOfferOfLand',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Bank Statement for 12 Months',
    controlName: 'personalBankStatementFor12Months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: '5-Year Financial Projections',
    controlName: 'financialProjectionsFor5years',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Balance Sheets of all Shareholders',
    controlName: 'personalBalanceSheetsOfAllShareholders',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Valuation Report',
    controlName: 'valuationReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deed of Sale',
    controlName: 'deedOfSale',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Proof of Title Deed',
    controlName: 'proofOfTitleDeed',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Bills of Quantity',
    controlName: 'billsOfQuantity',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Structural Report',
    controlName: 'structuralReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Land Usage',
    controlName: 'usageOfLand',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Citizenship Status',
    controlName: 'isCitizens',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Due Diligence Report',
    controlName: 'dueDilligenceReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Livestock Brand Certificate',
    controlName: 'livestockBrandCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Livestock Census',
    controlName: 'livestockCensus',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Letter of Intent',
    controlName: 'letterOfIntent',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations of Items',
    controlName: 'threeQuationsOfItems',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Insurance Quotations',
    controlName: 'insuranceQuotations',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Soil and Water Tests Report',
    controlName: 'soilAndWaterTestsReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Borehole Drilling Completion',
    controlName: 'boreholeDrillingCompletion',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Map of Existing Borehole',
    controlName: 'mapOfExistingBoreHole',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Concent From Land Board',
    controlName: 'consentFromLandBoard',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Copy of Lease Agreement',
    controlName: 'copyOfLeaseAgreement',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Professional and Academic Certificates',
    controlName: 'professionalAndAcadamicCertificates',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Tax Clearance Certificate',
    controlName: 'taxClearanceCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Marriage Certificate',
    controlName: 'marriageCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deeds of Marriage Instrument',
    controlName: 'deedsMarriageInstrument',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Environmental Impact Assessment',
    controlName: 'environmentImpactAssessment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Ranch Ecology Site',
    controlName: 'ranchEcologySite',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Additional Documents',
    controlName: 'addDocs',
    numberOfDocs: 10,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
];

export const documentRequiredByServicesSector: LoanApplicationDocuments[] = [
  {
    labelName: 'Audited Financial Statements',
    controlName: 'auditedFinancialStatements',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Application Form and Business Plan',
    controlName: 'applicationFormAndBusinessPlan',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Certified Copies of Omang',
    controlName: 'certifiedCopiesOfOmang',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Resolution by Board of Directors',
    controlName: 'resolutionByBod',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 2',
    controlName: 'form2',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 3',
    controlName: 'form3',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 4',
    controlName: 'form4',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Bank Statement for 12 Months',
    controlName: 'personalBankStatementFor12Months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: '5-Year Financial Projections',
    controlName: 'financialProjectionsFor5years',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Balance Sheets of all Shareholders',
    controlName: 'personalBalanceSheetsOfAllShareholders',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Valuation Report',
    controlName: 'valuationReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deed of Sale',
    controlName: 'deedOfSale',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Proof of Title Deed',
    controlName: 'proofOfTitleDeed',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Bills of Quantity',
    controlName: 'billsOfQuantity',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Structural Report',
    controlName: 'structuralReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Citizenship Status',
    controlName: 'isCitizens',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Due Diligence Report',
    controlName: 'dueDilligenceReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Letter of Intent',
    controlName: 'letterOfIntent',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations of Items',
    controlName: 'threeQuationsOfItems',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Insurance Quotations',
    controlName: 'insuranceQuotations',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Soil and Water Tests Report',
    controlName: 'soilAndWaterTestsReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Professional and Academic Certificates',
    controlName: 'professionalAndAcadamicCertificates',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Tax Clearance Certificate',
    controlName: 'taxClearanceCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Marriage Certificate',
    controlName: 'marriageCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deeds of Marriage Instrument',
    controlName: 'deedsMarriageInstrument',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Environmental Impact Assessment',
    controlName: 'environmentImpactAssessment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Copy of Lease Agreement',
    controlName: 'copyOfLeaseAgreement',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Copy of Necessary License to Operate',
    controlName: 'copyOfNecessaryLicensesToOperate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations for Proposed Development',
    controlName: 'threeQuotationsForProposedDevelopment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Memorandum and Articles of Association',
    controlName: 'moaa',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Proof of Ownership',
    controlName: 'proofOfOwnership',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Franchisee Agreement',
    controlName: 'franchiseeAgreement',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Additional Documents',
    controlName: 'addDocs',
    numberOfDocs: 10,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
];

export const documentRequiredByPropertySector: LoanApplicationDocuments[] = [
  {
    labelName: 'Audited Financial Statements',
    controlName: 'auditedFinancialStatements',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Application Form and Business Plan',
    controlName: 'applicationFormAndBusinessPlan',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Certified Copies of Omang',
    controlName: 'certifiedCopiesOfOmang',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Resolution by Board of Directors',
    controlName: 'resolutionByBod',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 2',
    controlName: 'form2',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 3',
    controlName: 'form3',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 4',
    controlName: 'form4',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Bank Statement for 12 Months',
    controlName: 'personalBankStatementFor12Months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: '5-Year Financial Projections',
    controlName: 'financialProjectionsFor5years',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Balance Sheets of all Shareholders',
    controlName: 'personalBalanceSheetsOfAllShareholders',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Valuation Report',
    controlName: 'valuationReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deed of Sale',
    controlName: 'deedOfSale',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Proof of Title Deed',
    controlName: 'proofOfTitleDeed',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Bills of Quantity',
    controlName: 'billsOfQuantity',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Structural Report',
    controlName: 'structuralReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Citizenship Status',
    controlName: 'isCitizens',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Due Diligence Report',
    controlName: 'dueDilligenceReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Letter of Intent',
    controlName: 'letterOfIntent',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations of Items',
    controlName: 'threeQuationsOfItems',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Insurance Quotations',
    controlName: 'insuranceQuotations',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Soil and Water Tests Report',
    controlName: 'soilAndWaterTestsReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Professional and Academic Certificates',
    controlName: 'professionalAndAcadamicCertificates',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Tax Clearance Certificate',
    controlName: 'taxClearanceCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Marriage Certificate',
    controlName: 'marriageCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deeds of Marriage Instrument',
    controlName: 'deedsMarriageInstrument',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Environmental Impact Assessment',
    controlName: 'environmentImpactAssessment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Concept of Approved Architectural Plans',
    controlName: 'conceptOfArchitecturalApprovedPlans',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Copy of Lease Agreement',
    controlName: 'copyOfLeaseAgreement',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Copy of Necessary License to Operate',
    controlName: 'copyOfNecessaryLicensesToOperate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Three Quotations for Proposed Development',
    controlName: 'threeQuotationsForProposedDevelopment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Memorandum and Articles of Association',
    controlName: 'moaa',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Additional Documents',
    controlName: 'addDocs',
    numberOfDocs: 10,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
];

export const documentReqiredByManufacturingSector: LoanApplicationDocuments[] = [
  {
    labelName: 'Audited Financial Statements',
    controlName: 'auditedFinancialStatements',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Application Form and Business Plan',
    controlName: 'applicationFormAndBusinessPlan',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Business Bank Statement for 6 Months',
    controlName: 'businessBankStatementFor6months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Certified Copies of Omang',
    controlName: 'certifiedCopiesOfOmang',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Resolution by Board of Directors',
    controlName: 'resolutionByBod',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 2',
    controlName: 'form2',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 3',
    controlName: 'form3',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 4',
    controlName: 'form4',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Provisional Offer of Land',
    controlName: 'provisionalOfferOfLand',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Personal Bank Statement for 12 Months',
    controlName: 'personalBankStatementFor12Months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: '5-Year Financial Projections',
    controlName: 'financialProjectionsFor5years',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Balance Sheets of all Shareholders',
    controlName: 'personalBalanceSheetsOfAllShareholders',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Valuation Report',
    controlName: 'valuationReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deed of Sale',
    controlName: 'deedOfSale',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Proof of Title Deed',
    controlName: 'proofOfTitleDeed',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Bills of Quantity',
    controlName: 'billsOfQuantity',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Structural Report',
    controlName: 'structuralReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Citizenship Status',
    controlName: 'isCitizens',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Due Diligence Report',
    controlName: 'dueDilligenceReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Letter of Intent',
    controlName: 'letterOfIntent',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations of Items',
    controlName: 'threeQuationsOfItems',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Insurance Quotations',
    controlName: 'insuranceQuotations',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Soil and Water Tests Report',
    controlName: 'soilAndWaterTestsReport',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Professional and Academic Certificates',
    controlName: 'professionalAndAcadamicCertificates',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Tax Clearance Certificate',
    controlName: 'taxClearanceCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Marriage Certificate',
    controlName: 'marriageCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Deeds of Marriage Instrument',
    controlName: 'deedsMarriageInstrument',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Environmental Impact Assessment',
    controlName: 'environmentImpactAssessment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Concept of Approved Architectural Plans',
    controlName: 'conceptOfArchitecturalApprovedPlans',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },

  {
    labelName: 'Copy of Lease Agreement',
    controlName: 'copyOfLeaseAgreement',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Copy of Necessary License to OperateCopy of Necessary Licenses to Operate',
    controlName: 'copyOfNecessaryLicensesToOperate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations for Proposed Development',
    controlName: 'threeQuotationsForProposedDevelopment',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Memorandum and Articles of Association',
    controlName: 'moaa',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Additional Documents',
    controlName: 'addDocs',
    numberOfDocs: 10,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
];

export const documentRequiredByTradeFinanceSector: LoanApplicationDocuments[] = [
  {
    labelName: 'Application Form and Business Plan',
    controlName: 'applicationFormAndBusinessPlan',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Company Profile',
    controlName: 'companyProfile',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Market Information',
    controlName: 'market',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Certified Copies of Omang',
    controlName: 'certifiedCopiesOfOmang',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Resolution by Board of Directors',
    controlName: 'resolutionByBod',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 2',
    controlName: 'form2',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 3',
    controlName: 'form3',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 4',
    controlName: 'form4',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Form 5',
    controlName: 'form5',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Historic Financial Statements',
    controlName: 'historicFinancials',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Personal Bank Statement for 12 Months',
    controlName: 'personalBankStatementFor12Months',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Financial Projections',
    controlName: 'financialProjections',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Market Information',
    controlName: 'market',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'CVs of Shareholders',
    controlName: 'cvOfShareHolders',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Copy of Necessary License to Operate',
    controlName: 'copyOfNecessaryLicensesToOperate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Three Quotations of Items',
    controlName: 'threeQuationsOfItems',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Tax Clearance Certificate',
    controlName: 'taxClearanceCertificate',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Memorandum and Articles of Association',
    controlName: 'moaa',
    numberOfDocs: 1,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
  {
    labelName: 'Additional Documents',
    controlName: 'addDocs',
    numberOfDocs: 10,
    maxUploadSize: 10,
    fileExtensionType: '.jpg,.jpeg,.png,.pdf',
    addInformation: '',
    required: true,
  },
];
