export interface MabogoDinkuDocumentFile {
  id: number;
  documentType: string;
  documentDescription: string;
  docPath: string;
  docName: string;
  individualId?: any;
}
export interface MabogoDinkuDocsModel {
  groupBankAccountOpeningConfirmationLetter: MabogoDinkuDocumentFile[];
  certifiedCopiesOfOmang: MabogoDinkuDocumentFile[];
  threeQuationsOfItems: MabogoDinkuDocumentFile;
  consentFromLandBoard: MabogoDinkuDocumentFile;
  letterOfRequest: MabogoDinkuDocumentFile | null;
  financialProjectionsFor5years: MabogoDinkuDocumentFile;
  signedGroupConstitution: MabogoDinkuDocumentFile[];
  boreholeDrillingCompletion: MabogoDinkuDocumentFile;
  cvOfShareHolders: MabogoDinkuDocumentFile[];
  ranchEcologySite: MabogoDinkuDocumentFile;
  usageOfLand: MabogoDinkuDocumentFile;
  mapOfExistingBoreHole: MabogoDinkuDocumentFile;
  livestockBrandCertificate: MabogoDinkuDocumentFile;
  personalBalanceSheetsOfAllShareholders: MabogoDinkuDocumentFile;
  copyOfOmangForEachGroupMember: MabogoDinkuDocumentFile[];
  businessBankStatementFor6months: MabogoDinkuDocumentFile;
  copyOfNecessaryLicensesToOperate: MabogoDinkuDocumentFile | null;
  form5: MabogoDinkuDocumentFile | null;
  proofOfResidence: MabogoDinkuDocumentFile | null;
  form4: MabogoDinkuDocumentFile;
  provisionalOfferOfLand: MabogoDinkuDocumentFile;
  spouseMarriedId: MabogoDinkuDocumentFile | null;
  completedApplicationForm: MabogoDinkuDocumentFile | null;
  market: MabogoDinkuDocumentFile | null;
  franchiseeAgreement: MabogoDinkuDocumentFile | null;
  deedsMarriageInstrument: MabogoDinkuDocumentFile;
  copyOfLeaseAgreement: MabogoDinkuDocumentFile;
  leaseAgreement: MabogoDinkuDocumentFile | null;
  applicationFormAndBusinessPlan: MabogoDinkuDocumentFile;
  deedOfSale: MabogoDinkuDocumentFile;
  addDoc1: MabogoDinkuDocumentFile | null;
  addDoc2: MabogoDinkuDocumentFile | null;
  addDoc5: MabogoDinkuDocumentFile | null;
  groupBankAccountStatement: MabogoDinkuDocumentFile[];
  addDoc6: MabogoDinkuDocumentFile | null;
  form3: MabogoDinkuDocumentFile;
  addDoc3: MabogoDinkuDocumentFile | null;
  form2: MabogoDinkuDocumentFile;
  addDoc4: MabogoDinkuDocumentFile | null;
  addDoc9: MabogoDinkuDocumentFile | null;
  addDoc7: MabogoDinkuDocumentFile | null;
  addDoc8: MabogoDinkuDocumentFile | null;
  quotationForItemToFinanced: MabogoDinkuDocumentFile | null;
  taxClearanceCertificate: MabogoDinkuDocumentFile;
  proofOfPhysicalAddress: MabogoDinkuDocumentFile | null;
  proofOfPastBusinessActivity: MabogoDinkuDocumentFile[];
  groupMustHaveFiveToFifteenMember: MabogoDinkuDocumentFile[];
  financialProjections: MabogoDinkuDocumentFile | null;
  livestockCensus: MabogoDinkuDocumentFile;
  environmentImpactAssessment: MabogoDinkuDocumentFile;
  proofOfOwnership: MabogoDinkuDocumentFile | null;
  personalBankStatementFor12Months: MabogoDinkuDocumentFile;
  groupMemberMustResideWithingTwentyKm: MabogoDinkuDocumentFile[];
  companyProfile: MabogoDinkuDocumentFile | null;
  groupStartUpsRatio: MabogoDinkuDocumentFile[];
  proofOfEmploymentAndSalaryForEmployedMember: MabogoDinkuDocumentFile[];
  bankAccountConfirmationLetter: MabogoDinkuDocumentFile | null;
  proofOfTitleDeed: MabogoDinkuDocumentFile;
  addDoc10: MabogoDinkuDocumentFile | null;
  employedMemberIncome: MabogoDinkuDocumentFile[];
  professionalAndAcadamicCertificates: MabogoDinkuDocumentFile[];
  threeQuotationsForProposedDevelopment: MabogoDinkuDocumentFile[] | null;
  dueDilligenceReport: MabogoDinkuDocumentFile;
  marriageCertificate: MabogoDinkuDocumentFile;
  soilAndWaterTestsReport: MabogoDinkuDocumentFile;
  structuralReport: MabogoDinkuDocumentFile;
  conceptOfArchitecturalApprovedPlans: MabogoDinkuDocumentFile | null;
  additionalDocument: MabogoDinkuDocumentFile[];
  valuationReport: MabogoDinkuDocumentFile;
  resolutionByBod: MabogoDinkuDocumentFile;
  moaa: MabogoDinkuDocumentFile | null;
  creditWorthinessReport: MabogoDinkuDocumentFile[];
  billsOfQuantity: MabogoDinkuDocumentFile;
  approvedArchitecturalDrawings: MabogoDinkuDocumentFile | null;
  insuranceQuotations: MabogoDinkuDocumentFile;
  historicFinancials: MabogoDinkuDocumentFile | null;
  isCitizens: MabogoDinkuDocumentFile;
  letterOfIntent: MabogoDinkuDocumentFile;
  addDocs: MabogoDinkuDocumentFile[];
  auditedFinancialStatements: MabogoDinkuDocumentFile;
  disabilityDocument: MabogoDinkuDocumentFile[];
  cleanCreditCheckDocs: MabogoDinkuDocumentFile[];
  adverseCreditCheckDocs: MabogoDinkuDocumentFile[];
  fillStatus?: boolean;
}
