import { StatusTableModel } from './status-table.model';

export const statusTableDummyData: StatusTableModel[] = [
  {
    id: 1,
    name: 'John Doe',
    description: 'Lorem ipsum dolor sit amet.',
    status: 'approved',
    date: '2023-07-20',
    action: 'Edit',
  },
  {
    id: 2,
    name: 'Jane Smith',
    description: 'Consectetur adipiscing elit.',
    status: 'rejected',
    date: '2023-07-19',
    action: 'Delete',
  },
  {
    id: 3,
    name: 'Mike Johnson',
    description: 'Sed do eiusmod tempor incididunt ut labore.',
    status: 'approved',
    date: '2023-07-18',
    action: 'View',
  },
  {
    id: 4,
    name: 'Sarah Brown',
    description: 'Ut enim ad minim veniam.',
    status: 'approved',
    date: '2023-07-17',
    action: 'Edit',
  },
  {
    id: 5,
    name: 'Alex Green',
    description: 'Duis aute irure dolor in reprehenderit.',
    status: 'rejected',
    date: '2023-07-16',
    action: 'Delete',
  },
  {
    id: 6,
    name: 'Emily White',
    description: 'Excepteur sint occaecat cupidatat non proident.',
    status: 'approved',
    date: '2023-07-15',
    action: 'View',
  },
  {
    id: 7,
    name: 'Robert Lee',
    description: 'Sunt in culpa qui officia deserunt mollit.',
    status: 'approved',
    date: '2023-07-14',
    action: 'Edit',
  },
  {
    id: 8,
    name: 'Olivia Davis',
    description: 'Eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: 'rejected',
    date: '2023-07-13',
    action: 'Delete',
  },
  {
    id: 9,
    name: 'William Clark',
    description: 'Nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    status: 'approved',
    date: '2023-07-12',
    action: 'View',
  },
  {
    id: 10,
    name: 'Sophia Adams',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    status: 'approved',
    date: '2023-07-11',
    action: 'Edit',
  },
];
