interface CountryCode {
  name: string;
  dialCode: string;
  code: string;
  flagIcon: string;
}

const CountriesCodes: CountryCode[] = [
  // Repeating the same country to make it appear on top of the list
  // Default
  {
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
    flagIcon: 'botswana.svg',
  },

  // Other

  {
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
    flagIcon: 'afghanistan.svg',
  },
  {
    name: 'Åland Islands',
    dialCode: '+358',
    code: 'AX',
    flagIcon: 'aland-islands.svg',
  },
  {
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
    flagIcon: 'albania.svg',
  },
  {
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
    flagIcon: 'algeria.svg',
  },
  {
    name: 'American Samoa',
    dialCode: '+1-684',
    code: 'AS',
    flagIcon: 'american-samoa.svg',
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
    flagIcon: 'andorra.svg',
  },
  {
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
    flagIcon: 'angola.svg',
  },
  {
    name: 'Anguilla',
    dialCode: '+1-264',
    code: 'AI',
    flagIcon: 'anguilla.svg',
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '+1-268',
    code: 'AG',
    flagIcon: 'antigua-and-barbuda.svg',
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
    flagIcon: 'argentina.svg',
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
    flagIcon: 'armenia.svg',
  },
  {
    name: 'Aruba',
    dialCode: '+297',
    code: 'AW',
    flagIcon: 'aruba.svg',
  },
  {
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
    flagIcon: 'australia.svg',
  },
  {
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
    flagIcon: 'austria.svg',
  },
  {
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
    flagIcon: 'azerbaijan.svg',
  },
  {
    name: 'Azores Islands',
    dialCode: '+351',
    code: 'PT-20',
    flagIcon: 'azores-islands.svg',
  },
  {
    name: 'Bahamas',
    dialCode: '+1-242',
    code: 'BS',
    flagIcon: 'bahamas.svg',
  },
  {
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
    flagIcon: 'bahrain.svg',
  },
  {
    name: 'Balearic Islands',
    dialCode: '+34',
    code: 'ES-IB',
    flagIcon: 'balearic-islands.svg',
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
    flagIcon: 'bangladesh.svg',
  },
  {
    name: 'Barbados',
    dialCode: '+1-246',
    code: 'BB',
    flagIcon: 'barbados.svg',
  },
  {
    name: 'Basque Country',
    dialCode: '+34',
    code: 'ES-CN',
    flagIcon: 'basque-country.svg',
  },
  {
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
    flagIcon: 'belarus.svg',
  },
  {
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
    flagIcon: 'belgium.svg',
  },
  {
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
    flagIcon: 'belize.svg',
  },
  {
    name: 'Benin',
    dialCode: '+229',
    code: 'BJ',
    flagIcon: 'benin.svg',
  },
  {
    name: 'Bermuda',
    dialCode: '+1-441',
    code: 'BM',
    flagIcon: 'bermuda.svg',
  },
  {
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
    flagIcon: 'bhutan.svg',
  },
  {
    name: 'Bolivia',
    dialCode: '+591',
    code: 'BO',
    flagIcon: 'bolivia.svg',
  },
  {
    name: 'Bonaire',
    dialCode: '+599',
    code: 'BQ',
    flagIcon: 'bonaire.svg',
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
    flagIcon: 'bosnia-and-herzegovina.svg',
  },

  {
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
    flagIcon: 'brazil.svg',
  },
  {
    name: 'British Columbia',
    dialCode: '+1-236',
    code: 'CA-BC',
    flagIcon: 'british-columbia.svg',
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
    flagIcon: 'british-indian-ocean-territory.svg',
  },
  {
    name: 'British Virgin Islands',
    dialCode: '+1-284',
    code: 'VG',
    flagIcon: 'british-virgin-islands.svg',
  },
  {
    name: 'Brunei',
    dialCode: '+673',
    code: 'BN',
    flagIcon: 'brunei.svg',
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
    flagIcon: 'bulgaria.svg',
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
    flagIcon: 'burkina-faso.svg',
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
    flagIcon: 'burundi.svg',
  },
  {
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
    flagIcon: 'cambodia.svg',
  },
  {
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
    flagIcon: 'cameroon.svg',
  },
  {
    name: 'Canada',
    dialCode: '+1',
    code: 'CA',
    flagIcon: 'canada.svg',
  },
  {
    name: 'Canary Islands',
    dialCode: '+34',
    code: 'ES-IC',
    flagIcon: 'canary-islands.svg',
  },
  {
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
    flagIcon: 'cape-verde.svg',
  },
  {
    name: 'Cayman Islands',
    dialCode: '+1-345',
    code: 'KY',
    flagIcon: 'cayman-islands.svg',
  },
  {
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
    flagIcon: 'central-african-republic.svg',
  },
  {
    name: 'Ceuta',
    dialCode: '+34',
    code: 'ES-CE',
    flagIcon: 'ceuta.svg',
  },
  {
    name: 'Chad',
    dialCode: '+235',
    code: 'TD',
    flagIcon: 'chad.svg',
  },
  {
    name: 'Chile',
    dialCode: '+56',
    code: 'CL',
    flagIcon: 'chile.svg',
  },
  {
    name: 'China',
    dialCode: '+86',
    code: 'CN',
    flagIcon: 'china.svg',
  },
  {
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
    flagIcon: 'christmas-island.svg',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
    flagIcon: 'cocos-island.svg',
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
    flagIcon: 'colombia.svg',
  },
  {
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
    flagIcon: 'comoros.svg',
  },
  {
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
    flagIcon: 'cook-islands.svg',
  },
  {
    name: 'Corsica',
    dialCode: '+33',
    code: 'FR-20',
    flagIcon: 'corsica.svg',
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
    flagIcon: 'costa-rica.svg',
  },
  {
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
    flagIcon: 'croatia.svg',
  },
  {
    name: 'Cuba',
    dialCode: '+53',
    code: 'CU',
    flagIcon: 'cuba.svg',
  },
  {
    name: 'Curaçao',
    dialCode: '+599',
    code: 'CW',
    flagIcon: 'curacao.svg',
  },
  // {
  //   name: 'Cyprus',
  //   dialCode: '+357',
  //   code: 'CY',
  //   flagIcon: 'cyprus.svg',
  // },
  {
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
    flagIcon: 'czech-republic.svg',
  },
  {
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
    flagIcon: 'denmark.svg',
  },
  {
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
    flagIcon: 'djibouti.svg',
  },
  {
    name: 'Dominica',
    dialCode: '+1-767',
    code: 'DM',
    flagIcon: 'dominica.svg',
  },
  {
    name: 'Dominican Republic',
    dialCode: '+1-809',
    code: 'DO',
    flagIcon: 'dominican-republic.svg',
  },
  {
    name: 'East Timor',
    dialCode: '+670',
    code: 'TL',
    flagIcon: 'east-timor.svg',
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
    flagIcon: 'ecuador.svg',
  },
  {
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
    flagIcon: 'egypt.svg',
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
    flagIcon: 'el-salvador.svg',
  },
  {
    name: 'England',
    dialCode: '+44',
    code: 'GB-ENG',
    flagIcon: 'england.svg',
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
    flagIcon: 'equatorial-guinea.svg',
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
    flagIcon: 'eritrea.svg',
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
    flagIcon: 'estonia.svg',
  },
  {
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
    flagIcon: 'ethiopia.svg',
  },
  {
    name: 'European Union',
    dialCode: '+358',
    code: 'EU',
    flagIcon: 'european-union.svg',
  },
  {
    name: 'Falkland Islands',
    dialCode: '+500',
    code: 'FK',
    flagIcon: 'falkland-islands.svg',
  },
  // {
  //   name: 'Faroe Islands',
  //   dialCode: '+298',
  //   code: 'FO',
  //   flagIcon: 'faroe-islands.svg',
  // },
  {
    name: 'Fiji',
    dialCode: '+679',
    code: 'FJ',
    flagIcon: 'fiji.svg',
  },
  {
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
    flagIcon: 'finland.svg',
  },
  {
    name: 'France',
    dialCode: '+33',
    code: 'FR',
    flagIcon: 'france.svg',
  },
  // {
  //   name: 'French Guiana',
  //   dialCode: '+594',
  //   code: 'GF',
  //   flagIcon: 'french-guiana.svg',
  // },
  {
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
    flagIcon: 'french-polynesia.svg',
  },
  {
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
    flagIcon: 'gabon.svg',
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
    flagIcon: 'gambia.svg',
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
    flagIcon: 'georgia.svg',
  },
  {
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
    flagIcon: 'germany.svg',
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
    flagIcon: 'ghana.svg',
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
    flagIcon: 'gibraltar.svg',
  },
  {
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
    flagIcon: 'greece.svg',
  },
  {
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
    flagIcon: 'greenland.svg',
  },
  {
    name: 'Grenada',
    dialCode: '+1-473',
    code: 'GD',
    flagIcon: 'grenada.svg',
  },
  // {
  //   name: 'Guadeloupe',
  //   dialCode: '+590',
  //   code: 'GP',
  //   flagIcon: 'guadeloupe.svg',
  // },
  {
    name: 'Guam',
    dialCode: '+1-671',
    code: 'GU',
    flagIcon: 'guam.svg',
  },
  {
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
    flagIcon: 'guatemala.svg',
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
    flagIcon: 'guernsey.svg',
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
    flagIcon: 'guinea.svg',
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
    flagIcon: 'guinea-bissau.svg',
  },
  // {
  //   name: 'Guyana',
  //   dialCode: '+592',
  //   code: 'GY',
  //   flagIcon: 'guyana.svg',
  // },
  {
    name: 'Haiti',
    dialCode: '+509',
    code: 'HT',
    flagIcon: 'haiti.svg',
  },
  {
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
    flagIcon: 'honduras.svg',
  },
  {
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
    flagIcon: 'hong-kong.svg',
  },
  {
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
    flagIcon: 'hungary.svg',
  },
  {
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
    flagIcon: 'iceland.svg',
  },
  {
    name: 'India',
    dialCode: '+91',
    code: 'IN',
    flagIcon: 'india.svg',
  },
  {
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
    flagIcon: 'indonesia.svg',
  },
  {
    name: 'Iran',
    dialCode: '+98',
    code: 'IR',
    flagIcon: 'iran.svg',
  },
  {
    name: 'Iraq',
    dialCode: '+964',
    code: 'IQ',
    flagIcon: 'iraq.svg',
  },
  {
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
    flagIcon: 'ireland.svg',
  },
  {
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
    flagIcon: 'isle-of-man.svg',
  },
  {
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
    flagIcon: 'israel.svg',
  },
  {
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
    flagIcon: 'italy.svg',
  },
  {
    name: 'Ivory Coast',
    dialCode: '+225',
    code: 'CI',
    flagIcon: 'ivory-coast.svg',
  },
  {
    name: 'Jamaica',
    dialCode: '+1-876',
    code: 'JM',
    flagIcon: 'jamaica.svg',
  },
  {
    name: 'Japan',
    dialCode: '+81',
    code: 'JP',
    flagIcon: 'japan.svg',
  },
  {
    name: 'Jersey',
    dialCode: '+44',
    code: 'JE',
    flagIcon: 'jersey.svg',
  },
  {
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
    flagIcon: 'jordan.svg',
  },
  {
    name: 'Kazakhstan',
    dialCode: '+7',
    code: 'KZ',
    flagIcon: 'kazakhstan.svg',
  },
  {
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
    flagIcon: 'kenya.svg',
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
    flagIcon: 'kiribati.svg',
  },
  {
    name: 'Kosovo',
    dialCode: '+383',
    code: 'XK',
    flagIcon: 'kosovo.svg',
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
    flagIcon: 'kuwait.svg',
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
    flagIcon: 'kyrgyzstan.svg',
  },
  {
    name: 'Laos',
    dialCode: '+856',
    code: 'LA',
    flagIcon: 'laos.svg',
  },
  {
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
    flagIcon: 'latvia.svg',
  },
  {
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
    flagIcon: 'lebanon.svg',
  },
  {
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
    flagIcon: 'lesotho.svg',
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
    flagIcon: 'liberia.svg',
  },
  {
    name: 'Libya',
    dialCode: '+218',
    code: 'LY',
    flagIcon: 'libya.svg',
  },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
    flagIcon: 'liechtenstein.svg',
  },
  {
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
    flagIcon: 'lithuania.svg',
  },
  {
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
    flagIcon: 'luxembourg.svg',
  },
  {
    name: 'Macau',
    dialCode: '+853',
    code: 'MO',
    flagIcon: 'macao.svg',
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
    flagIcon: 'madagascar.svg',
  },
  {
    name: 'Madeira',
    dialCode: '+351',
    code: 'PT-30',
    flagIcon: 'madeira.svg',
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
    flagIcon: 'malawi.svg',
  },
  {
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
    flagIcon: 'malaysia.svg',
  },
  {
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
    flagIcon: 'maldives.svg',
  },
  {
    name: 'Mali',
    dialCode: '+223',
    code: 'ML',
    flagIcon: 'mali.svg',
  },
  {
    name: 'Malta',
    dialCode: '+356',
    code: 'MT',
    flagIcon: 'malta.svg',
  },
  // {
  //   name: 'Marshall Islands',
  //   dialCode: '+692',
  //   code: 'MH',
  //   flagIcon: 'marshall-islands.svg',
  // },
  {
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
    flagIcon: 'martinique.svg',
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
    flagIcon: 'mauritania.svg',
  },
  {
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
    flagIcon: 'mauritius.svg',
  },
  {
    name: 'Melilla',
    dialCode: '+34',
    code: 'ES-ML',
    flagIcon: 'melilla.svg',
  },
  {
    name: 'Mexico',
    dialCode: '+52',
    code: 'MX',
    flagIcon: 'mexico.svg',
  },
  {
    name: 'Micronesia',
    dialCode: '+691',
    code: 'FM',
    flagIcon: 'micronesia.svg',
  },
  {
    name: 'Moldova',
    dialCode: '+373',
    code: 'MD',
    flagIcon: 'moldova.svg',
  },
  {
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
    flagIcon: 'monaco.svg',
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
    flagIcon: 'mongolia.svg',
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
    flagIcon: 'montenegro.svg',
  },
  {
    name: 'Montserrat',
    dialCode: '+1-664',
    code: 'MS',
    flagIcon: 'montserrat.svg',
  },
  {
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
    flagIcon: 'morocco.svg',
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
    flagIcon: 'mozambique.svg',
  },
  {
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
    flagIcon: 'myanmar.svg',
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
    flagIcon: 'namibia.svg',
  },
  {
    name: 'Nauru',
    dialCode: '+674',
    code: 'NR',
    flagIcon: 'nauru.svg',
  },
  {
    name: 'Nepal',
    dialCode: '+977',
    code: 'NP',
    flagIcon: 'nepal.svg',
  },
  {
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
    flagIcon: 'netherlands.svg',
  },
  // {
  //   name: 'New Caledonia',
  //   dialCode: '+687',
  //   code: 'NC',
  //   flagIcon: 'new-caledonia.svg',
  // },
  {
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
    flagIcon: 'new-zealand.svg',
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
    flagIcon: 'nicaragua.svg',
  },
  {
    name: 'Niger',
    dialCode: '+227',
    code: 'NE',
    flagIcon: 'niger.svg',
  },
  {
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
    flagIcon: 'nigeria.svg',
  },
  {
    name: 'Niue',
    dialCode: '+683',
    code: 'NU',
    flagIcon: 'niue.svg',
  },
  {
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
    flagIcon: 'norfolk-island.svg',
  },
  {
    name: 'North Korea',
    dialCode: '+850',
    code: 'KP',
    flagIcon: 'north-korea.svg',
  },
  // {
  //   name: 'North Macedonia',
  //   dialCode: '+389',
  //   code: 'MK',
  //   flagIcon: 'north-macedonia.svg',
  // },
  // {
  //   name: 'Northern Ireland',
  //   dialCode: '+44',
  //   code: 'GB-NIR',
  //   flagIcon: 'northern-ireland.svg',
  // },
  {
    name: 'Northern Mariana Islands',
    dialCode: '+1-670',
    code: 'MP',
    flagIcon: 'northern-mariana-islands.svg',
  },
  {
    name: 'Norway',
    dialCode: '+47',
    code: 'NO',
    flagIcon: 'norway.svg',
  },
  {
    name: 'Oman',
    dialCode: '+968',
    code: 'OM',
    flagIcon: 'oman.svg',
  },
  {
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
    flagIcon: 'pakistan.svg',
  },
  {
    name: 'Palau',
    dialCode: '+680',
    code: 'PW',
    flagIcon: 'palau.svg',
  },
  {
    name: 'Palestine',
    dialCode: '+970',
    code: 'PS',
    flagIcon: 'palestine.svg',
  },
  {
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
    flagIcon: 'panama.svg',
  },
  {
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
    flagIcon: 'papua-new-guinea.svg',
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
    flagIcon: 'paraguay.svg',
  },
  {
    name: 'Peru',
    dialCode: '+51',
    code: 'PE',
    flagIcon: 'peru.svg',
  },
  {
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
    flagIcon: 'philippines.svg',
  },
  {
    name: 'Pitcairn Islands',
    dialCode: '+64',
    code: 'PN',
    flagIcon: 'pitcairn-islands.svg',
  },
  {
    name: 'Poland',
    dialCode: '+48',
    code: 'PL',
    flagIcon: 'poland.svg',
  },
  {
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
    flagIcon: 'portugal.svg',
  },
  {
    name: 'Puerto Rico',
    dialCode: '+1-787, +1-939',
    code: 'PR',
    flagIcon: 'puerto-rico.svg',
  },
  {
    name: 'Qatar',
    dialCode: '+974',
    code: 'QA',
    flagIcon: 'qatar.svg',
  },
  // {
  //   name: 'Réunion',
  //   dialCode: '+262',
  //   code: 'RE',
  //   flagIcon: 'reunion.svg',
  // },
  {
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
    flagIcon: 'romania.svg',
  },
  {
    name: 'Russia',
    dialCode: '+7',
    code: 'RU',
    flagIcon: 'russia.svg',
  },
  {
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
    flagIcon: 'rwanda.svg',
  },
  // {
  //   name: 'Saint Barthélemy',
  //   dialCode: '+590',
  //   code: 'BL',
  //   flagIcon: 'saint-barthelemy.svg',
  // },
  // {
  //   name: 'Saint Helena, Ascension and Tristan da Cunha',
  //   dialCode: '+290',
  //   code: 'SH',
  //   flagIcon: 'saint-helena-ascension-tristan-da-cunha.svg',
  // },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '+1-869',
    code: 'KN',
    flagIcon: 'saint-kitts-and-nevis.svg',
  },
  // {
  //   name: 'Saint Lucia',
  //   dialCode: '+1-758',
  //   code: 'LC',
  //   flagIcon: 'saint-lucia.svg',
  // },
  // {
  //   name: 'Saint Martin',
  //   dialCode: '+590',
  //   code: 'MF',
  //   flagIcon: 'saint-martin.svg',
  // },
  // {
  //   name: 'Saint Pierre and Miquelon',
  //   dialCode: '+508',
  //   code: 'PM',
  //   flagIcon: 'saint-pierre-and-miquelon.svg',
  // },
  // {
  //   name: 'Saint Vincent and the Grenadines',
  //   dialCode: '+1-784',
  //   code: 'VC',
  //   flagIcon: 'saint-vincent-and-the-grenadines.svg',
  // },
  {
    name: 'Samoa',
    dialCode: '+685',
    code: 'WS',
    flagIcon: 'samoa.svg',
  },
  {
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
    flagIcon: 'san-marino.svg',
  },
  // {
  //   name: 'São Tomé and Príncipe',
  //   dialCode: '+239',
  //   code: 'ST',
  //   flagIcon: 'sao-tome-and-principe.svg',
  // },
  {
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
    flagIcon: 'saudi-arabia.svg',
  },
  {
    name: 'Scotland',
    dialCode: '+44',
    code: 'GB-SCT',
    flagIcon: 'scotland.svg',
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
    flagIcon: 'senegal.svg',
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
    flagIcon: 'serbia.svg',
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
    flagIcon: 'seychelles.svg',
  },
  {
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
    flagIcon: 'sierra-leone.svg',
  },
  {
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
    flagIcon: 'singapore.svg',
  },
  {
    name: 'Sint Maarten',
    dialCode: '+1-721',
    code: 'SX',
    flagIcon: 'sint-maarten.svg',
  },
  {
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
    flagIcon: 'slovakia.svg',
  },
  {
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
    flagIcon: 'slovenia.svg',
  },
  {
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
    flagIcon: 'solomon-islands.svg',
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
    flagIcon: 'somalia.svg',
  },
  {
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
    flagIcon: 'south-africa.svg',
  },
  // {
  //   name: 'South Georgia and the South Sandwich Islands',
  //   dialCode: '+500',
  //   code: 'GS',
  //   flagIcon: 'south-georgia-and-the-south-sandwich-islands.svg',
  // },
  {
    name: 'South Korea',
    dialCode: '+82',
    code: 'KR',
    flagIcon: 'south-korea.svg',
  },
  {
    name: 'South Sudan',
    dialCode: '+211',
    code: 'SS',
    flagIcon: 'south-sudan.svg',
  },
  {
    name: 'Spain',
    dialCode: '+34',
    code: 'ES',
    flagIcon: 'spain.svg',
  },
  {
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
    flagIcon: 'sri-lanka.svg',
  },
  {
    name: 'Sudan',
    dialCode: '+249',
    code: 'SD',
    flagIcon: 'sudan.svg',
  },
  {
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
    flagIcon: 'suriname.svg',
  },
  // {
  //   name: 'Svalbard and Jan Mayen',
  //   dialCode: '+47',
  //   code: 'SJ',
  //   flagIcon: 'svalbard-and-jan-mayen.svg',
  // },
  {
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
    flagIcon: 'swaziland.svg',
  },
  {
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
    flagIcon: 'sweden.svg',
  },
  {
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
    flagIcon: 'switzerland.svg',
  },
  {
    name: 'Syria',
    dialCode: '+963',
    code: 'SY',
    flagIcon: 'syria.svg',
  },
  {
    name: 'Taiwan',
    dialCode: '+886',
    code: 'TW',
    flagIcon: 'taiwan.svg',
  },
  {
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
    flagIcon: 'tajikistan.svg',
  },
  {
    name: 'Tanzania',
    dialCode: '+255',
    code: 'TZ',
    flagIcon: 'tanzania.svg',
  },
  {
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
    flagIcon: 'thailand.svg',
  },
  {
    name: 'Togo',
    dialCode: '+228',
    code: 'TG',
    flagIcon: 'togo.svg',
  },
  {
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
    flagIcon: 'tokelau.svg',
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
    flagIcon: 'tonga.svg',
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '+1-868',
    code: 'TT',
    flagIcon: 'trinidad-and-tobago.svg',
  },
  {
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
    flagIcon: 'tunisia.svg',
  },
  {
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
    flagIcon: 'turkey.svg',
  },
  {
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
    flagIcon: 'turkmenistan.svg',
  },
  // {
  //   name: 'Turks and Caicos Islands',
  //   dialCode: '+1-649',
  //   code: 'TC',
  //   flagIcon: 'turks-and-caicos-islands.svg',
  // },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
    flagIcon: 'tuvalu.svg',
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
    flagIcon: 'uganda.svg',
  },
  {
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
    flagIcon: 'ukraine.svg',
  },
  {
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
    flagIcon: 'united-arab-emirates.svg',
  },
  {
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
    flagIcon: 'united-kingdom.svg',
  },
  {
    name: 'United States',
    dialCode: '+1',
    code: 'US',
    flagIcon: 'united-states.svg',
  },
  {
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
    flagIcon: 'uruguay.svg',
  },
  {
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
    flagIcon: 'uzbekistan.svg',
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
    flagIcon: 'vanuatu.svg',
  },
  {
    name: 'Vatican City',
    dialCode: '+379',
    code: 'VA',
    flagIcon: 'vatican-city.svg',
  },
  {
    name: 'Venezuela',
    dialCode: '+58',
    code: 'VE',
    flagIcon: 'venezuela.svg',
  },
  {
    name: 'Vietnam',
    dialCode: '+84',
    code: 'VN',
    flagIcon: 'vietnam.svg',
  },
  // {
  //   name: 'Virgin Islands, British',
  //   dialCode: '+1-284',
  //   code: 'VG',
  //   flagIcon: 'virgin-islands-british.svg',
  // },
  // {
  //   name: 'Virgin Islands, U.S.',
  //   dialCode: '+1-340',
  //   code: 'VI',
  //   flagIcon: 'virgin-islands-us.svg',
  // },
  {
    name: 'Wales',
    dialCode: '+44',
    code: 'GB-WLS',
    flagIcon: 'wales.svg',
  },
  // {
  //   name: 'Wallis and Futuna',
  //   dialCode: '+681',
  //   code: 'WF',
  //   flagIcon: 'wallis-and-futuna.svg',
  // },
  // {
  //   name: 'Western Sahara',
  //   dialCode: '+212',
  //   code: 'EH',
  //   flagIcon: 'western-sahara.svg',
  // },
  {
    name: 'Yemen',
    dialCode: '+967',
    code: 'YE',
    flagIcon: 'yemen.svg',
  },
  {
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
    flagIcon: 'zambia.svg',
  },
  {
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
    flagIcon: 'zimbabwe.svg',
  },
];

// export interface and countriesCodes ES6
export { CountryCode, CountriesCodes };
