export const RequiredIndividualFields: any = {
  title: 'Title',
  fullName: 'First Name',
  surname: 'Last Name',
  dateOfBirth: 'Date of Birth',
  maritalStatus: 'Marital Status',

  mobileNumber: 'Mobile Number',
  // mobileNumberStatus: 'Mobile Number Verification',
  gender: 'Gender',
  nationality: 'Nationality',
  addrPlot: 'Standard Address: Street Name',
  addrSuburb: 'Standard Address: House Number',
  addrTown: 'Standard Address: Postal Code / City',
  postalAddrPoBox: 'Standard Address: Postal Address',
  postalAddrTown: 'Standard Address: Postal Address Town',
  addrCountry: 'Standard Address: Country',
  hvAddrPlot: 'Home Village Address: Street Name',
  hvAddrSuburb: 'Home Village Address: House Number',
  hvAddrTown: 'Home Village Address: Village',
  hvAddrCountry: 'Home Village Address: Country',
  nkAddrPlot: 'KIN Address: Street Name',
  nkAddrSuburb: 'KIN Address: House Number',
  nkAddrTown: 'KIN Address: Postal Code / City',
  nkAddrCountry: 'KIN Address: Country',
  nkContact: 'KIN Address: Contact',
  nkName: 'KIN Address: Name',
  nkRelationship: 'KIN Address: Relationship',
  nkAddrPlot2: 'KIN Address 2: Street Name',
  nkAddrSuburb2: 'KIN Address 2: House Number',
  nkAddrTown2: 'KIN Address 2: Postal Code / City',
  nkAddrCountry2: 'KIN Address 2: Country',
  nkContact2: 'KIN Address 2: Contact',
  nkName2: 'KIN Address 2: Name',
  nkRelationship2: 'KIN Address 2: Relationship',

  disability: 'Disability',
  disabilityType: 'Disability Type',
  nkSurname: 'KIN Address: Surname',
  nkSurname2: 'KIN Address 2: Surname',
  creditCheck: 'Credit Check',

  // confilict
  foreignPassportExpiry: 'Passport Expiry Date',
  foreignPassportNumber: 'Passport Number',

  omangNumber: 'Omang Number',
  dateOfOmangExpiry: 'Omang Expiry Date',
};
